# -*- coding: utf-8 -*-
import subprocess

command = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":30}',
    "--model-name",
    "self_impl.VAR_model",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "ILI/VAR",
]

command1 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "fixed_forecast_config_daily.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":60}',
    "--model-name",
    "self_impl.VAR_model",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "ILI/VAR",
]
path = "./scripts/run_benchmark.py"

command2 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":14}',
    "--model-name",
    "time_series_library.NLinear",
    "--model-hyper-params",
    '{"batch_size": 16, "d_ff": 512, "d_model": 256, "lr": 0.01, "horizon": 14, "seq_len": 36}',
    "--adapter",
    "transformer_adapter",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "FRED/NLinear",
]

command3 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":24}',
    "--model-name",
    "time_series_library.NLinear",
    "--model-hyper-params",
    '{"k": 2, "horizon": 96, "seq_len": 336, "d_ff": 64, "d_model": 8,"num_nodes":11, "learning_rate":0.0005, "batch_size":256, "gpu":6, "patch_size_list":[[42, 24, 12, 16],[42, 28, 16, 12], [16, 28, 12, 42]]}',
    "--adapter",
    "transformer_adapter",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "FRED/NLinear",
]

command4 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":30}',
    "--model-name",
    "time_series_library.FiLM",
    "--model-hyper-params",
    '{"dropout": 0.05, "factor": 3, "lr": 0.01, "moving_avg": 25, "num_epochs": 60, "patience": 10, "horizon": 30, "seq_len": 60, "d_ff": 2048, "d_model": 512}',
    "--adapter",
    "transformer_adapter",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "ILI/FiLM",
]

command5 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":30}',
    "--model-name",
    "pathformer.Pathformer",
    "--model-hyper-params",
    '{"k": 1, "horizon": 21, "seq_len": 104, "d_ff": 64, "d_model": 2,"num_nodes":7, "patch_size_list":[[13, 4, 8, 2],[13, 8, 4, 2], [4, 8, 8, 4]], "batch_norm":0,  "learning_rate":0.0003, "residual_connection":1, "batch_size":24, "lradj":"TST"}',
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "ILI/Pathformer",
]

command6 = [
    "python",
    "./scripts/run_benchmark.py",
    "--config-path",
    "rolling_forecast_config.json",
    "--data-name-list",
    "TSA1-26.csv",
    "--strategy-args",
    '{"horizon":14}',
    "--model-name",
    "time_series_library.Crossformer",
    "--model-hyper-params",
    '{"d_ff": 512, "d_model": 256, "dropout": 1, "e_layers": 2, "factor": 10, "lr": 0.0005, "n_heads": 4, "num_epochs": 20, "horizon": 14, "seg_len": 6, "seq_len": 104}',
    "--adapter",
    "transformer_adapter",
    "--gpus",
    "0",
    "--num-workers",
    "1",
    "--timeout",
    "60000",
    "--save-path",
    "ILI/Crossformer",
]
subprocess.run(command6)

# subprocess.run(command)
